### PR TITLE
Fixed ipc connection promising resolution

### PR DESCRIPTION
**Pull request by rodrigopavezi**

### CODE REVIEW

**Comment by stulees** [comment]
@rodrigopavezi As it turns out I found a problem in the flow of the design doc and think we need to start LM first before all other modules. If we start all modules (no order), player may connect to LM before launcher does. Player will send the player-load-complete message but launcher may not be able to receive it yet. 

By starting LM first before all modules, it will ensure a connection is available for all modules when they try to broadcast or receive. Given that, I don't think the changes in this PR are required (unfortunately). Thoughts?

**Comment by rodrigopavezi** [comment]
@stulees oh, I see. I still think we should make this changes because of other scenarios we found where it may create unnecessary connection to LMS which could be a mess. @tejohnso Thoughts? cheers

**Comment by tejohnso** [comment]
@rodrigopavezi How would it create unnecessary connections? If broadcast is called it's going to return any existing lmsClient if one was already created.

**Comment by rodrigopavezi** [comment]
@tejohnso so you are sure LM will always be available before any other module? cheers

**Comment by rodrigopavezi** [comment]
@tejohnso I mean it could create multiple connections if there are multiple calls to connect before if connect for the first time. cheers

**Comment by tejohnso** [comment]
@rodrigopavezi yes, but also, I  don't think we need to prevent the return of lmsClient until after the connection is made.  I think 

```
lmsClient={...}
resolve(lmsClient)
```

can go outside of the `on connect`

**Comment by rodrigopavezi** [comment]
@tejohnso I think that will cause an issue because if we resolve the promise before lmsClient is created brodcastMessage will try to call lmsClient.broadcastMessage which will not exist until it is connected. Thoughts? cheers

**Comment by tejohnso** [comment]
@rodrigopavezi I think I see what you mean. ipc.of.lms won't exist.  I'm not sure what node-ipc is going to do in that case but it's not worth investigating at this point if this works the way you've got it.

**Comment by rodrigopavezi** [comment]
@stulees do you agree to go with this changes too? cheers

**Comment by stulees** [comment]
@rodrigopavezi Okay 👍

**Pull request merged**
